# Generated by Django 3.1.1 on 2021-06-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_dp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retirees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField()),
                ('effectivity_date', models.DateField()),
                ('assign_ghq', models.BooleanField()),
                ('created_by', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('pers_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unit_dp.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Of_Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_purpose', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_sos', models.CharField(max_length=255, null=True)),
                ('uploaded_cmd_clearance', models.CharField(max_length=255, null=True)),
                ('accountability', models.BooleanField()),
                ('uploaded_unit_clearance', models.CharField(max_length=255, null=True)),
                ('unit_status', models.BooleanField()),
                ('purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unit_dp.type_of_purpose')),
                ('ret_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unit_dp.retirees')),
            ],
        ),
        migrations.AddField(
            model_name='retirees',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unit_dp.type_of_purpose'),
        ),
    ]
