# Generated by Django 3.1.1 on 2021-06-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_dp', '0002_auto_20210622_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirees',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='retirees',
            name='date_applied',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='retirees',
            name='effectivity_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
