# Generated by Django 3.1.1 on 2021-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_dp', '0003_auto_20210622_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirees',
            name='assign_ghq',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], max_length=20, null=True),
        ),
    ]
