# Generated by Django 3.1.1 on 2021-06-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_dp', '0009_auto_20210623_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit_requirements',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='retirees',
            name='assign_ghq',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='unit_requirements',
            name='uploaded_unit_clearance',
            field=models.FileField(blank=True, null=True, upload_to='unit_clearance'),
        ),
    ]
